### ISSUE TITLE
Linting in VSCode?

### ISSUE THREAD

**Issue by BrunoCartier** [tighten/duster#139]
I'm an avid user of your "tlint" plugin on VSCode. I use it to see the various errors in red, directly in the IDE, next to the lines of code.
I'd like to find a similar "developer experience" with Duster, i.e. not activate automatic formatting on saving, but be able to correct errors myself when writing code.

What approach could I use (there don't seem to be any plug-ins available)? For example, does Duster offer a "json" output mode that could be used directly in the VSCode tlint plugin? Or do I need to install and configure an individual plugin for each sub-tool offered by Duster? If so, what configurations should I give them?

Thanks in advance.

**Comment by driftingly** [comment]
There aren't any Duster IDE plugins to accomplish this. Since Duster packages a few tools, you may be able to accomplish this by downloading Duster as a source and configuring the IDE plugins for each tool to point to Duster's configuration files.

You can checkout Duster's `composer.json` file to see how we pull in Pint's source.
